### ISSUE TITLE
Не понял, что тебе не нравится?  Массив знаков пунктуации можно выделить в отдельное поле, тебе не нравилось писать все знаки пунктуации в методе?

### ISSUE THREAD

**Issue by Avel7884** [kontur-courses/tdd#50]
_Originally posted by @lurlrlrl in https://github.com/kontur-courses/tdd/pull/32_

Не нравится что появляется ответственность за полноту списка знаков пунктуации.

**Comment by Avel7884** [comment]
Я случайно(

**Comment by lurlrlrl** [comment]
Ох. Я и не думал придираться к таким мелочам, сейчас  ты например не пытаешься избавиться от символов валют в тексте, зачем тогда думать о редких знаках пунктуации?

Старайся не писать сложные методы, если можно воспользоваться встроенными возможностями .NET Framework. Например можно было воспользоваться Regex.Split().

А вообще я бы лучше использовал другой подход, например найти в текст все последователности символов латиницы(или кириллицы).
